import type { Activity } from "@/types/activity";
import type { Deal } from "@/types/deal";
import type { Lead } from "@/types/lead";
import type { AuthUser, Workspace } from "@/types/workspace";

export const mockWorkspaces: Workspace[] = [
  { id: "1", slug: "acme", name: "Acme Vendas", plan: "pro" },
  { id: "2", slug: "startup-x", name: "Startup X", plan: "free" },
];

export const mockUser: AuthUser = {
  id: "1",
  name: "Lilian Moretti",
  email: "lilian@pipeflow.com",
  role: "admin",
};

export interface MockMember {
  id: string;
  name: string;
}

export const mockMembers: MockMember[] = [
  { id: "1", name: "Lilian Moretti" },
  { id: "2", name: "Bruno Alves" },
  { id: "3", name: "Camila Souza" },
];

export const mockLeads: Lead[] = [
  {
    id: "1",
    workspaceId: "1",
    name: "Rafael Nogueira",
    email: "rafael.nogueira@construtech.com.br",
    phone: "(11) 98211-4432",
    company: "ConstruTech Engenharia",
    jobTitle: "Diretor Comercial",
    status: "novo",
    ownerId: "1",
    createdAt: "2026-07-15",
  },
  {
    id: "2",
    workspaceId: "1",
    name: "Juliana Ferraz",
    email: "juliana.ferraz@nordesteagro.com.br",
    phone: "(85) 99123-7765",
    company: "Nordeste Agro",
    jobTitle: "Gerente de Compras",
    status: "contatado",
    ownerId: "2",
    createdAt: "2026-07-14",
  },
  {
    id: "3",
    workspaceId: "1",
    name: "Marcos Vinícius Tavares",
    email: "marcos.tavares@lojafuturo.com.br",
    phone: "(21) 97654-1298",
    company: "Loja Futuro",
    jobTitle: "Sócio-fundador",
    status: "qualificado",
    ownerId: "1",
    createdAt: "2026-07-12",
  },
  {
    id: "4",
    workspaceId: "1",
    name: "Patrícia Lemos",
    email: "patricia.lemos@grupolemos.com.br",
    phone: "(31) 98877-5566",
    company: "Grupo Lemos Distribuição",
    jobTitle: "Coordenadora de Vendas",
    status: "convertido",
    ownerId: "3",
    createdAt: "2026-07-10",
  },
  {
    id: "5",
    workspaceId: "1",
    name: "Eduardo Cavalcanti",
    email: "eduardo.cavalcanti@cavalcantiadv.com.br",
    phone: "(81) 99345-2210",
    company: "Cavalcanti Advogados",
    jobTitle: "Sócio",
    status: "perdido",
    ownerId: "2",
    createdAt: "2026-07-08",
  },
  {
    id: "6",
    workspaceId: "1",
    name: "Fernanda Bittencourt",
    email: "fernanda.bittencourt@saudeviva.com.br",
    phone: "(51) 98456-7723",
    company: "Saúde Viva Clínicas",
    jobTitle: "Gerente Administrativa",
    status: "novo",
    ownerId: "1",
    createdAt: "2026-07-18",
  },
  {
    id: "7",
    workspaceId: "1",
    name: "Thiago Machado",
    email: "thiago.machado@machadocontabil.com.br",
    phone: "(41) 99012-3345",
    company: "Machado Contabilidade",
    jobTitle: "Diretor",
    status: "contatado",
    ownerId: "3",
    createdAt: "2026-07-16",
  },
  {
    id: "8",
    workspaceId: "1",
    name: "Larissa Prado",
    email: "larissa.prado@pradoimoveis.com.br",
    phone: "(19) 98765-4321",
    company: "Prado Imóveis",
    jobTitle: "Corretora Chefe",
    status: "qualificado",
    ownerId: "1",
    createdAt: "2026-07-11",
  },
  {
    id: "9",
    workspaceId: "1",
    name: "Gustavo Henrique Ramos",
    email: "gustavo.ramos@ramoslogistica.com.br",
    phone: "(47) 99234-8890",
    company: "Ramos Logística",
    jobTitle: "Gerente de Operações",
    status: "novo",
    ownerId: "2",
    createdAt: "2026-07-19",
  },
  {
    id: "10",
    workspaceId: "2",
    name: "Isabela Correia",
    email: "isabela.correia@startupx.io",
    phone: "(11) 98123-9988",
    company: "Startup X Cliente Beta",
    jobTitle: "Head de Produto",
    status: "qualificado",
    ownerId: "1",
    createdAt: "2026-07-13",
  },
  {
    id: "11",
    workspaceId: "2",
    name: "Vinícius Andrade",
    email: "vinicius.andrade@andradetech.com.br",
    phone: "(48) 99887-6655",
    company: "Andrade Tech",
    jobTitle: "CTO",
    status: "contatado",
    ownerId: "1",
    createdAt: "2026-07-09",
  },
  {
    id: "12",
    workspaceId: "2",
    name: "Camila Duarte",
    email: "camila.duarte@duartemarketing.com.br",
    phone: "(62) 99456-1123",
    company: "Duarte Marketing Digital",
    jobTitle: "CEO",
    status: "convertido",
    ownerId: "3",
    createdAt: "2026-07-07",
  },
  {
    id: "13",
    workspaceId: "1",
    name: "Roberto Salgado",
    email: "roberto.salgado@salgadotransportes.com.br",
    phone: "(27) 98234-5567",
    company: "Salgado Transportes",
    jobTitle: "Diretor Financeiro",
    status: "perdido",
    ownerId: "2",
    createdAt: "2026-07-05",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "1",
    workspaceId: "1",
    title: "Implantação CRM — ConstruTech",
    value: 18000,
    leadId: "1",
    ownerId: "1",
    dueDate: "2026-08-05",
    stage: "novo_lead",
    createdAt: "2026-07-15",
  },
  {
    id: "2",
    workspaceId: "1",
    title: "Licenças Pro — Saúde Viva",
    value: 9600,
    leadId: "6",
    ownerId: "1",
    dueDate: "2026-08-01",
    stage: "novo_lead",
    createdAt: "2026-07-18",
  },
  {
    id: "3",
    workspaceId: "1",
    title: "Expansão logística — Ramos",
    value: 24500,
    leadId: "9",
    ownerId: "2",
    dueDate: "2026-08-10",
    stage: "novo_lead",
    createdAt: "2026-07-19",
  },
  {
    id: "4",
    workspaceId: "1",
    title: "Contrato anual — Nordeste Agro",
    value: 31200,
    leadId: "2",
    ownerId: "2",
    dueDate: "2026-07-28",
    stage: "contato_realizado",
    createdAt: "2026-07-14",
  },
  {
    id: "5",
    workspaceId: "1",
    title: "Consultoria contábil — Machado",
    value: 7400,
    leadId: "7",
    ownerId: "3",
    dueDate: "2026-08-02",
    stage: "contato_realizado",
    createdAt: "2026-07-16",
  },
  {
    id: "6",
    workspaceId: "1",
    title: "Onboarding equipe — Loja Futuro",
    value: 15800,
    leadId: "3",
    ownerId: "1",
    dueDate: "2026-07-30",
    stage: "proposta_enviada",
    createdAt: "2026-07-12",
  },
  {
    id: "7",
    workspaceId: "1",
    title: "Upgrade Pro — Prado Imóveis",
    value: 12300,
    leadId: "8",
    ownerId: "1",
    dueDate: "2026-08-04",
    stage: "proposta_enviada",
    createdAt: "2026-07-11",
  },
  {
    id: "8",
    workspaceId: "1",
    title: "Integração faturamento — Salgado",
    value: 21000,
    leadId: "13",
    ownerId: "2",
    dueDate: "2026-07-26",
    stage: "negociacao",
    createdAt: "2026-07-05",
  },
  {
    id: "9",
    workspaceId: "1",
    title: "Plano anual — Grupo Lemos",
    value: 27600,
    leadId: "4",
    ownerId: "3",
    dueDate: "2026-07-22",
    stage: "fechado_ganho",
    createdAt: "2026-07-10",
  },
  {
    id: "10",
    workspaceId: "1",
    title: "Consultoria jurídica — Cavalcanti",
    value: 8900,
    leadId: "5",
    ownerId: "2",
    dueDate: "2026-07-20",
    stage: "fechado_perdido",
    createdAt: "2026-07-08",
  },
  {
    id: "11",
    workspaceId: "2",
    title: "Piloto beta — Startup X Cliente",
    value: 4200,
    leadId: "10",
    ownerId: "1",
    dueDate: "2026-08-06",
    stage: "novo_lead",
    createdAt: "2026-07-13",
  },
  {
    id: "12",
    workspaceId: "2",
    title: "Infra dedicada — Andrade Tech",
    value: 16700,
    leadId: "11",
    ownerId: "1",
    dueDate: "2026-08-08",
    stage: "contato_realizado",
    createdAt: "2026-07-09",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "1",
    leadId: "1",
    type: "nota",
    description:
      "Lead veio de indicação de cliente atual. Ainda não foi feito primeiro contato.",
    authorName: "Lilian Moretti",
    createdAt: "2026-07-15T09:30:00",
  },
  {
    id: "2",
    leadId: "2",
    type: "ligacao",
    description:
      "Primeira ligação de apresentação. Demonstrou interesse no plano Pro.",
    authorName: "Bruno Alves",
    createdAt: "2026-07-14T14:10:00",
  },
  {
    id: "3",
    leadId: "2",
    type: "email",
    description: "Enviado material institucional e tabela de preços.",
    authorName: "Bruno Alves",
    createdAt: "2026-07-14T16:45:00",
  },
  {
    id: "4",
    leadId: "3",
    type: "reuniao",
    description: "Reunião de descoberta com o time comercial da Loja Futuro.",
    authorName: "Lilian Moretti",
    createdAt: "2026-07-12T11:00:00",
  },
  {
    id: "5",
    leadId: "3",
    type: "nota",
    description: "Cliente pediu proposta com desconto para contrato anual.",
    authorName: "Lilian Moretti",
    createdAt: "2026-07-12T11:30:00",
  },
  {
    id: "6",
    leadId: "4",
    type: "ligacao",
    description: "Fechamento confirmado por telefone, aguardando contrato.",
    authorName: "Camila Souza",
    createdAt: "2026-07-10T15:20:00",
  },
  {
    id: "7",
    leadId: "4",
    type: "email",
    description: "Contrato enviado e assinado digitalmente.",
    authorName: "Camila Souza",
    createdAt: "2026-07-10T17:05:00",
  },
  {
    id: "8",
    leadId: "5",
    type: "reuniao",
    description: "Reunião final. Cliente optou por concorrente.",
    authorName: "Bruno Alves",
    createdAt: "2026-07-08T10:15:00",
  },
];
